frontend_sources: &frontend_sources
  - "frontend/**"
  - "enterprise/frontend/**"
  - "frontend/!(test)/**"
  - "yarn.lock"
  - "**/tsconfig*.json"
  - "package.json"
  - "babel.config.json"
  - "postcss.config.js"
  - "webpack.config.js"
  - "webpack.static-viz.config.js"

frontend_specs: &frontend_specs
  - "frontend/test/!(__support__|__runner__)/**"
  - "frontend/**.unit.*"
  - "jest.config.js"

frontend_all:
  - *frontend_sources
  - *frontend_specs

backend_sources: &backend_sources
  - "enterprise/backend/src/**"
  - "src/**"
  - "*modules/**"

backend_specs: &backend_specs
  - "test/**"
  - "enterprise/backend/test/**"

backend_all:
  - *backend_sources
  - *backend_specs

e2e_specs:
  - "**.cy.*.js"
  - "frontend/test/__support__/e2e/**"
  - "frontend/test/__runner__/*cypress*"

documentation:
  - "docs/**"
  - "**.md"
