name: Notify Pull Request
inputs:
  message:
    required: true
  include-log:
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: notify
      with:
        result-encoding: string
        script: |
          const message = "${{ inputs.message }}"
          const shouldIncludeLog = ${{ inputs.include-log }}.toString() === "true";
          const author = context.payload.sender.login;

          const issueNumber = (context.payload.issue && context.payload.issue.number) ||
                              (context.payload.pull_request && context.payload.pull_request.number);
          if (!issueNumber) {
            throw new Error("No issue or pull_request number found in context.payload");
          }

          let body = `@${author} ${message}`;

          if (shouldIncludeLog) {
            const { GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID } = process.env;
            const runUrl = `${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}`;
            body += ` [[Logs]](${runUrl})`;
          }

          github.rest.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body,
          });
