name: Auto-backport
on:
  pull_request:
    types: [closed, labeled]

jobs:
  create-backport:
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'backport') || github.event.label.name == 'backport')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: ./.github/actions/find-squashed-commit
        name: Find commit
        id: find_commit
        with:
          pull-request-number: ${{ github.event.pull_request.number }}

      - uses: ./.github/actions/get-latest-release-branch
        name: Get latest release branch
        id: get_latest_release_branch

      - uses: ./.github/actions/create-backport-pull-request
        name: Create backport pull request
        id: create_backport_pull_request
        with:
          target-branch: ${{ format('backport-{0}', github.event.pull_request.number) }}
          original-pull-request-number: ${{ github.event.pull_request.number }}
          original-title: ${{ github.event.pull_request.title }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ steps.find_commit.commit }}
