name: Backport automerge
on:
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1.6.0
        id: generate-token
        with:
          app_id: ${{ secrets.METABASE_BOT_APP_ID }}
          private_key: ${{ secrets.METABASE_BOT_APP_PRIVATE_KEY }}

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          MERGE_LABELS: "automerge,!wip"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "2"
          MERGE_RETRY_SLEEP: "5000"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: "true"
          MERGE_FILTER_AUTHOR: "metabase-bot-test[bot]"
          UPDATE_LABELS: ""
