# Cherry-picks commits from current branch to a specified one in a command "@metabase-bot backport release-x.40.x"
name: Backport

on:
  push:

jobs:
  create_pull_request:
    name: Creates a pull request
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: Cherry-pick commits and create PR
        with:
          fetch-depth: 0
      - uses: tibdex/github-app-token@v1.6.0
        id: generate-token
        with:
          app_id: ${{ secrets.MB_APP_ID }}
          private_key: ${{ secrets.MB_PRIVATE_KEY }}
      - name: Verify Membership
        uses: ./.github/actions/verify-membership
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          organization_name: scarab-engineering
          username: alxnddr
      - name: Log
        run: |
          echo "The user is a member of the organization: ${{ steps.verify_membership.outputs.is_member }}"
