name: E2E Tests for PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "docs/**"
      - "**.md"
      - ".circleci/**"
      - "**.unit.spec.*"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    name: e2e-tests-${{ matrix.folder }}${{ matrix.context }}-${{ matrix.edition }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [11]
        edition: [ee]
        folder:
          - "admin"
          - "binning"
          - "collections"
          - "custom-column"
          - "dashboard"
          - "dashboard-filters"
          - "downloads"
          - "embedding"
          - "filters"
          - "joins"
          - "models"
          - "native"
          - "native-filters"
          - "onboarding"
          - "organization"
          - "permissions"
          - "question"
          - "sharing"
          - "visualizations"
        include:
          - edition: oss
            context: grep
            java-version: 11
    steps:
      - run: 'echo "No build required" '
