name: Frontend

on:
  push:
    branches:
      - "master"
      - "release-**"
  pull_request:

jobs:
  fe-linter-prettier:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - run: yarn run lint-prettier
        name: Run Prettier formatting linter

  fe-linter-eslint:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - run: yarn run lint-eslint
        name: Run ESLint linter

  fe-type-check:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - run: yarn type-check
        name: Check types

  fe-tests-unit:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - run: yarn run test-unit --coverage --silent
        name: Run frontend unit tests
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: front-end
