name: Backend

on:
  push:
    branches:
      - "master"
      - "release-**"
  pull_request:
    branches:
      - "master"
      - "release-**"

jobs:
  files-changed:
    name: Check which files changed
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    outputs:
      backend_all: ${{ steps.changes.outputs.backend_all }}
    steps:
      - uses: actions/checkout@v3

      - name: Test which files changed
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-paths.yaml

  be-specs:
    needs: files-changed
    if: needs.files-changed.outputs.backend_all == 'true'
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "BE tests go brrr"
